### ISSUE TITLE
实例中的问题

### ISSUE THREAD

**Issue by dantangfan** [alex8224/gTornado#1]
跑了一下，实例中的test_mysql.py，实际上依然是同步执行的呀。

**Comment by alex8224** [comment]
@dantangfan 是tests/test_mysqld.py吗？
求你测试的用例
把最后几行改成下图然后在使用 time python test_mysqld.py看下测试结果是多少?
![image](https://cloud.githubusercontent.com/assets/574224/13388476/1ecf227e-defb-11e5-9083-d5ca12a86ba2.png)

然后再如下图所示,注释掉greenify的调用，然后再使用 time python test_mysqld.py看一下结果

![image](https://cloud.githubusercontent.com/assets/574224/13388501/69bd3df2-defb-11e5-91fd-2b9045f7ceb0.png)

**Comment by dantangfan** [comment]
嗯，代码就是test/test_mysqldb.py, 然后上面两种情况基本上是一样的。1000太大了，我改成了range(10)，耗时都是20s左右。
并且下面这份代码是可以工作的

```
import greenify
greenify.greenify()

import gevent
from gevent import monkey
monkey.patch_all()

#from pymysql import Connection
import torndb
assert greenify.patch_lib('/usr/lib64/mysql/libmysqlclient.so')
assert greenify.patch_lib('/usr/lib64/mysql/libmysqlclient_r.so')

import time
import random

def get_sql():
    return 'select sleep(0.01)'

def sync():
    s = time.time()
    conn = torndb.Connection(host="10.232.46.15:3306", user="xxx", password="xxx", database="xxx")
    for i in range(100):
        result = conn.query(get_sql())
    conn.close()

def async():
    s = time.time()

    def f():
        conn = torndb.Connection(host="10.232.46.15:3306", user="yld", password="yld@6874#~", database="yld")
        for i in range(10):
            conn.query(get_sql())
        conn.close()

    g = [gevent.spawn(f) for i in range(10)]
    gevent.joinall(g)


s = time.time()
for i in range(5):
    async()
print time.time() - s
print
s = time.time()
for i in range(5):
    sync()
print time.time() - s
```

async()耗时0.7s左右，sync()耗时5s左右。
系统信息
CentOS release 6.2，
Python 2.6.6
gevent==1.0.2
greenify==0.2.2
greenlet==0.4.9
tornado==4.2

**Comment by alex8224** [comment]
@dantangfan 明白了，你之前是不是已经安装了一个greenify(https://github.com/douban/greenify)? douban的那个greenify只支持gevent. 运行我的例子,你必须安装下面的greenify 
https://github.com/alex8224/greenify 这个是针对tornado做了适配的. 
**还有建议在 virtualenv中测试本项目．**

**Comment by dantangfan** [comment]
wow，原来是这样，thx！
